### ISSUE TITLE
Support broadcasting after download

### ISSUE THREAD

**Issue by HanniSchwabe** [aclap-dev/vdhcoapp#100]
Video DownloadHelper is a great extension, also for people who use Kodi to play streams from the internet on their TVs. To control Kodi directly from the PC, there are some "Cast to Kodi" browser extensions that are supposed to work like "Cast to Chrome" (that is, send the stream URL of an Internet source to Kodi), but unfortunately these extensions only support a few websites and often the extensions even do not find the correct URL on these few websites.
In contrast to Video DownloadHelper! Video DownloadHelper finds the correct URLs on many many websites!
Currently I use Video DownloadHelper to find the stream URL and I use a short VB script to send the URL to Kodi.
Would it be possible to integrate the second step (i.e. sending the URL to some target) into Video DownloadHelper? I attach the script 
[sendUrlToKodi.txt](https://github.com/mi-g/vdhcoapp/files/7026796/sendUrlToKodi.txt)
(I changed the extension from .vbs to .txt) but I think it would be sufficient to support something like shell:sendto - and every user could create his/her own script containing the details. And if one can set the command as default action then I can send the stream directly to Kodi with Video DownloadHelper, this would be great!

**Comment by paulrouget** [comment]
This issue hasn't had any activity in a long time, and it's not a feature we hear people want. I'm closing this issue.

If you still think this is relevant, please post in our dedicated forum: https://github.com/aclap-dev/video-downloadhelper/discussions
