### ISSUE TITLE
Brave not recognizing installed companion app.

### ISSUE THREAD

**Issue by Uradamus** [aclap-dev/vdhcoapp#102]
So I've been using this for years now with various browsers on Linux, mostly Firefox and Chrome/Chromium, so I'm fairly certain I am installing the companion app properly, especially since I am directly copying and pasting the commands from the install direction for (non-Debian) Linux and getting the appropriate output saying it is ready. But for whatever reason, Brave continues to act like it hasn't been installed. Though Firefox does seem to be using it properly.

I've dug around in the install dir a bit and found the config.json file which has empty square brackets for both Brave and Vivaldi, while the other entries for Firefox, Chrome, and Edge all seem to have some sort of unique identifier in them. I tried copying the one from Chrome into Brave, since Brave is one of those Chromium forks if I recall, but that didn't seem to do anything. I've restarted Brave both before and after copying that entry as well, didn't help any.

Am I just missing something, or is there something actually wrong here that needs to be rectified on your end with the code base?

**Comment by WolfangAukang** [comment]
For Brave, I set up this [PR](https://github.com/mi-g/vdhcoapp/pull/110) that fixes this in an user installation.

**Comment by paulrouget** [comment]
This is fixed in the next release. Hope to announce that next week.
