### ISSUE TITLE
Identified streams show only very low video quality ones

### ISSUE THREAD

**Issue by liar666** [aclap-dev/vdhcoapp#104]
Hi,

I'm sorry I'm posting this issue here, as I found no way to open a new "Conversations" in the Google's supported forum for the FF Addon...

I've updated my FF + FF Addons + VHH CoApp today to the latest versions.

When I start a YT video like
https://www.youtube.com/watch?v=Y2EboVOcikI
I can see it is available in all qualties, from poor to excellent:
![expl_quality](https://user-images.githubusercontent.com/3216927/133291259-af68ffa6-a987-44ea-96b1-23809f5cf79e.png)
However, VDH FF addon only lists ADP streams with very poor quality:
![expl_dwlhelper](https://user-images.githubusercontent.com/3216927/133291247-c9320ed7-0012-4b42-99d5-9c32e803bc38.png)

What is happening?

**Comment by paulrouget** [comment]
That's an add-on issue. Please post there: https://groups.google.com/g/video-downloadhelper-q-and-a
