### ISSUE TITLE
Flatpak firefox doesn't recognize vdhcoapp 

### ISSUE THREAD

**Issue by oshanz** [aclap-dev/vdhcoapp#114]
I use flatpak firefox(https://flathub.org/apps/details/org.mozilla.firefox). Installed the firefox addon and targz vdhcoapp on the user level. however, on download action addon seems not to recognize the vdhcoapp installation. it's throwing "This operation requires an external application to be completed."

![image](https://user-images.githubusercontent.com/5364479/147807448-14a76660-6ae8-45fb-a1ab-66aaa2262786.png)

![image](https://user-images.githubusercontent.com/5364479/147807348-f3cab135-ba5b-432f-85d3-2a113c0fe711.png)

 I've tried several combinations of settings to provide through flatseal(https://flathub.org/apps/details/com.github.tchx84.Flatseal). neither worked.

![image](https://user-images.githubusercontent.com/5364479/147806983-21afbd24-7c5c-4b6a-8245-bdf25abb7b23.png)

firefox version: 95
os: opensuse tumbleweed

**Comment by Jeoshua** [comment]
Same issue, this really needs to be fixed.

**Comment by knghtbrd** [comment]
As noted in #96 this is becoming a larger issue. Notably, Firefox on SteamDeck will also be Flatpak-only.

**Comment by leleleSDX** [comment]
We can't even make this program work in firejail. Running firefox outside of a sandbox makes god cry.

**Comment by Kurisu3** [comment]
So wouldn't it be possible to make it so that we can manually change the path to the CoApp in the browser extension settings and give it necessary permissions if needed ?

**Comment by mi-g** [comment]
Unfortunately, this is more complex. First, the coapp is located on an other filesystem than the browser (+extension) installed with snap/flatpack. Next, for security reasons, extensions have strictly no access to the native apps path. The browser API is in between and it requires declaring the coapp to the browser through manifest files. You can get more technical details by searching for "nativemessaging api".

**Comment by Kurisu3** [comment]
@mi-g  Thanks for your reply.
I created a desktop shortcut on Ubuntu 22.04 that runs `/snap/firefox/current/usr/lib/firefox/firefox` and now it works fine as well as other extensions that have the same problem like uget-integrator .

I suspect this may not be recommended and will require reinstalling extensions after each snap firefox update.

**Comment by mi-g** [comment]
Indeed, executing the snap-installed version from the top level filesystem path does the trick, thanks for sharing !
It is important to understand that doing this removes the snap sandboxing security feature (same as if you install Firefox manually). Also, the browser user profile is different when you run Firefox from snap or top-level.

**Comment by pizzadude** [comment]
1. Extract the vdhcoapp somewhere in your home directory, let's say /home/user/net.downloadhelper.coapp
2. Make the directory ~/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts if it doesn't already exist
3. Copy net.downloadhelper.coapp.json into the directory. The file should look like this:
```
{
    "name": "net.downloadhelper.coapp",
    "description": "Video DownloadHelper companion app",
    "path": "/home/user/net.downloadhelper.coapp/bin/net.downloadhelper.coapp-linux-64",
    "type": "stdio",
    "allowed_extensions": [
        "weh-native-test@downloadhelper.net",
        "{b9db16a4-6edc-47ec-a1f4-b86292ed211d}"
    ]
}
```
4. Whitelist vdhcoapp dir " ~/net.downloadhelper.coapp " using Flatseal or flatpak override
5. ???
6. Profit!

**Comment by SifiW** [comment]
You can remove the snap Firefox and reinstall through PPA and the companion app will be found. https://github.com/mi-g/vdhcoapp/issues/133#issuecomment-1165334764

**Comment by jntesteves** [comment]
Installing for Firefox Flatpak is super easy, it just needs a small adaptation to the [installation instructions](https://www.downloadhelper.net/install-coapp#extra-targz64):

```
tar xf net.downloadhelper.coapp-1.6.3-1_amd64.tar.gz -C ~/.var/app/org.mozilla.firefox
flatpak run --command=$HOME/.var/app/org.mozilla.firefox/net.downloadhelper.coapp-1.6.3/bin/net.downloadhelper.coapp-linux-64 org.mozilla.firefox install --user
```

I'd also recommend changing the default download folder in the extension's settings to `~/Downloads`. No messing with permissions necessary.

**Comment by paulrouget** [comment]
Is this still a problem with the latest version of Firefox? It's supposed to have been fixed.

**Comment by paulrouget** [comment]
Closing in favor of https://github.com/aclap-dev/vdhcoapp/issues/159
