### ISSUE TITLE
Support Apple Silicon on macOS

### ISSUE THREAD

**Issue by sharp-pixel** [aclap-dev/vdhcoapp#115]
Currently, macOS support is for x86_64 architecture and building for arm64 (Apple Silicon) is non-trivial due to multiple project dependencies.
This architecture should be supported and releases should include an Apple Silicon version.

**Comment by KrasnayaPloshchad** [comment]
I think this could be done by integrating FFmpeg 5.x release.

**Comment by macbugs** [comment]
When aggregating the components of a 1.25 hour DASH streaming video after download, the process is surprisingly slow
— it takes over 2.5 hours with all 8 cores operating at 100% load.

- build FFMPEG on Apple Silicon

[GitHub - ssut/ffmpeg-on-apple-silicon: Build ffmpeg for ARM-based Apple Silicon Macs](https://github.com/ssut/ffmpeg-on-apple-silicon)

[GitHub - Vargol/ffmpeg-apple-arm64-build: Build script for ffmpeg targeting the latest open source video codecs running on macOS using Apple's M1 processor.](https://github.com/Vargol/ffmpeg-apple-arm64-build)

The `MacYTDL` application can install the ARM64 version of FFMPEG.  It can also be installed via HomeBrew — but in either case, VideoDownloadHelper will still use the bundled Intel version at `/Applications/net.downloadhelper.coapp.app/Contents/MacOS/converter/build/mac/64`

> [_“MacYTDL can now install ARM64 version of FFmpeg/FFprobe and the user can switch to the Intel version if they wish”_](https://github.com/section83/MacYTDL/issues/52#issuecomment-1399404890)

How to tell the difference between FFMPEG versions on Mac:

## Method 1:

install [Apparency](https://www.mothersruin.com/software/Apparency/) and invoke QuickLook from the Finder on the FFMPEG binary

![Screenshot 2023-02-14 at 21 23 00](https://user-images.githubusercontent.com/101867641/218924137-6f8bca30-48c0-49c7-9f9d-948cb1062ac9.png)
![Screenshot 2023-02-14 at 21 22 13](https://user-images.githubusercontent.com/101867641/218924153-d763d2a8-db3e-40fa-85ad-1de335150f9d.png)

## Method 2:

In Terminal, navigate to the folder which contains the version you want to check and run the binary with no arguments:

% `which ffmpeg`

(Homebrew version)
`/usr/local/bin/ffmpeg`

(bundled version)
`/Applications/net.downloadhelper.coapp.app/Contents/MacOS/converter/build/mac/64/ffmpeg`

`cd` [path]
% `./ffmpeg`

( Intel output )

```
ffmpeg version N-109856-gf8d6d0fbf1-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
```

( Apple Silicon output )

```
ffmpeg version 5.1.2-https://www.martin-riedl.de Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.102)
  configuration: --prefix=/Volumes/ffmpeg_arm64/out --enable-gpl --pkg-config-flags=--static --extra-version='https://www.martin-riedl.de' --enable-gray --enable-libxml2 --enable-libfreetype --enable-fontconfig --enable-libbluray --enable-libass --enable-libzvbi --enable-libaom --enable-libopenh264 --enable-librav1e --enable-libsvtav1 --enable-libvpx --enable-libx264 --enable-libx265 --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libtheora
```

**Comment by paulrouget** [comment]
This is fixed in the next release. Hope to announce that next week.
