### ISSUE TITLE
HLS streams break without error resulting in an incomplete download

### ISSUE THREAD

**Issue by tonsimple** [aclap-dev/vdhcoapp#116]
Basically what it says on the "tin can"
Sometimes HLS streams break without any error - the app reports successful download but only a part of video is downloaded.

Don't know how to debug it (it happens intermittently and produces no error)
The web player of the site from which download happens does not show any anomalies (so unlikely to be a "site side problem") and browser downloads aren't interrupted (so does not appear to be a network issue)

**Comment by tonsimple** [comment]
Additional info - I was able to download the offending video completely using https://m3u8.dev/ video extractor operating in TS mode (their MP4 download feature is rather poor, but their TS mode absolute rocks, is blazing fast, reliable and even provides useful info)

That tool even provided what might be useful info, specifically, it complained of "false fragmentation" (and re-downloading / reloading / trying from a different machine did not change anything)
Using the feature to force it to download available healthy slices did download the video, with surprisingly little corruption.

Note:
the https://m3u8.dev/ HLS download is much MUCH faster and much more reliable than vdhcoapp, provides useful feedback and a method of recovering from "false fragmentation" (whatever that is, but it seems to be the cause of my woes) with minimum losses.
Maybe you could look into borrowing their approach?

**Comment by paulrouget** [comment]
The upcoming coapp + vdh implement a new download strategy (and you should see the speedup and correctness improvements). See https://groups.google.com/g/video-downloadhelper-q-and-a/c/JZ3HSPh8bL8
