### ISSUE TITLE
Error when communicating with the native messaging host. (Edge)

### ISSUE THREAD

**Issue by floatas** [aclap-dev/vdhcoapp#117]
I tried to install this extension in Chrome and in Edge - both browsers show same error.
Anyone has idea what I'm missing ? how to debug this issue ?

Installed edge from:  https://microsoftedge.microsoft.com/addons/detail/video-downloadhelper/jmkaglaafmhbcpleggkmaliipiilhldn

Video DownloadHelper
Version 7.6.0.0
Browser locale: en-US
Production build
Built on Wed Jun 30 2021 19:47:54 GMT+0200 (Central European Summer Time)
Build options: browser=edge

Companion app version: 1.6.3

**Comment by vanowm** [comment]
Pretty sure they use "custom" version with additional commands.

**Comment by paulrouget** [comment]
This has been working for some time now.
Is it still happening?

**Comment by paulrouget** [comment]
Works here. If this is still happening to you, please re-open this issue, and mention:

- where you see this error
- which OS you're using
