### ISSUE TITLE
V1.6.3 is not setting the version string correctly

### ISSUE THREAD

**Issue by chbwien** [aclap-dev/vdhcoapp#118]
V1.6.3 does not set the version string correctly during the installation. Therefore winget gets into a loop. See https://github.com/microsoft/winget-pkgs/issues/44897

**Comment by Wandrer** [comment]
Any update to this? Adding a version string can't be that hard to fix, right?

**Comment by alanlivio** [comment]
Many thanks @Str0mfresser. 
@mi-g, can you accept this PR it seems very straightforward.
