### ISSUE TITLE
Error write EPIPE

### ISSUE THREAD

**Issue by Unprogress** [aclap-dev/vdhcoapp#121]
Happens when i want to download videos from ANY website.
Also happens when i want to change the default download location.
It just loops the name in the background counting up.

Only solution so far is to use the fast download button. 
Reinstalling is not working, neither for the extension itself nor for the CoApp.

Also happens on Firefox.

Version used:
Video DownloadHelper
Version 7.6.0.0
Browsersprache: de
Produktionsversion
Kompilierungszeitpunkt: Wed Jun 30 2021 19:47:29 GMT+0200 (Central European Summer Time)
Kompilierungsoptionen: browser=chrome, noyt=true

Plattform: Win x86-64
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36

Begleitanwendung gefunden: VdhCoApp 1.6.2
Pfad zur Begleitanwendung: C:\Program Files\net.downloadhelper.coapp\bin\net.downloadhelper.coapp-win-64.exe

Bought license.

**Comment by paulrouget** [comment]
Not actionnable.
