### ISSUE TITLE
Nicer name in add/remove programs on Windows?

### ISSUE THREAD

**Issue by OneOfMany07** [aclap-dev/vdhcoapp#126]
I was cleaning out old programs from add/remove programs (aka Apps & features in Windows 10), and I'd forgotten what "VdhCoApp 1.6.3" was and had to spend time searching to figure it out.  Would it be easy to add a bit clearer name in that area?  Like "Video Download Helper CoApp 1.6.3"?

Is this an electron app?  I'd found a package.json file that seemed like a possible source for the string, and when I searched online that tool was the top few results.  They seem to have settings for Windows that could be enabled...

https://github.com/electron/electron-packager/pull/63

I assume they have settings for other platforms too, like Mac...

**Comment by paulrouget** [comment]
Fixed in master. Should be part of the next release (the name is "downloadhelper coapp" in the new installer)
