### ISSUE TITLE
Native messaging host manifest file for Microsoft Edge missing from Linux .deb installer

### ISSUE THREAD

**Issue by norweeg** [aclap-dev/vdhcoapp#131]
the Linux .deb installer does **not** install a native messaging host manifest file to `/etc/opt/edge/native-messaging-hosts` per [Microsoft's Native Messaging documentation](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/native-messaging?tabs=linux#step-3---copy-the-native-messaging-host-manifest-file-to-your-system), preventing the Edge browser from being able to communicate with vdhcoapp.  Creating `/etc/opt/edge/native-messaging-hosts/net.downloadhelper.coapp.json` manually with the contents below works around the issue, however this file should be created/installed when installing from the .deb file

```json
{
    "name": "net.downloadhelper.coapp",
    "description": "Video DownloadHelper companion app",
    "path": "/opt/net.downloadhelper.coapp/bin/net.downloadhelper.coapp-linux-64",
    "type": "stdio",
    "allowed_origins": [
        "chrome-extension://jmkaglaafmhbcpleggkmaliipiilhldn/"
    ]
}
```

**Comment by paulrouget** [comment]
Should be fixed in master. Next release should include Edge.
