### ISSUE TITLE
Cannot download video

### ISSUE THREAD

**Issue by raffaem** [aclap-dev/vdhcoapp#132]
Hello,

I cannot download [this video](https://www.seznamzpravy.cz/clanek/zahranicni-video-splnili-nemozne-ukrajinsti-piloti-se-dostali-do-mariupolu-a-zpet-204463).

When I click on the only 1280x720 video, it will start to download it, but when it reached 96%, it throws the following error

![Screenshot from 2022-06-01 11-12-49](https://user-images.githubusercontent.com/54762742/171370152-effb9f3f-44c0-46a8-b2fa-9c3d6b101b70.png)

**Comment by paulrouget** [comment]
This is a add-on support request. Please post here: https://groups.google.com/g/video-downloadhelper-q-and-a

**Comment by paulrouget** [comment]
This is a add-on support request. Please post here: https://groups.google.com/g/video-downloadhelper-q-and-a
