### ISSUE TITLE
Don't detected on ubuntu 22.04

### ISSUE THREAD

**Issue by mike9657** [aclap-dev/vdhcoapp#133]
I use firefox on ubuntu 22.04 LTS and installed vdhcoapp 1.6.3. When hit VDH it always reporting need install companion. But on ubuntu 20.04 it works correctly. How to solve the problem? Please.
Thanks.

**Comment by thing-bits** [comment]
Maybe is because you use the snap firefox package (is the version come by default)? the snap package are sanbox. Also the gnome extension not work.

**Comment by enekonieto** [comment]
I think there is no deb version of Firefox in Ubuntu 22.04, only the snap one. I have same problem than mike. Any workaround?

**Comment by enekonieto** [comment]
You can install Firefox from PPA following instructions in https://ubuntuhandbook.org/index.php/2022/04/install-firefox-deb-ubuntu-22-04/

**Comment by mike9657** [comment]
Thanks above all.
The problem has solved by remove snap package and re-install firefox from mozilla PPA.
Thanks thing-bits specially.

**Comment by paulrouget** [comment]
Closing in favor of https://github.com/aclap-dev/vdhcoapp/issues/159
