### ISSUE TITLE
could u provide a light install script ?

### ISSUE THREAD

**Issue by superiums** [aclap-dev/vdhcoapp#142]
currently, the installation includes a large appimage and utils (xdg-open, nodejs, ffmpeg, libs...), these should be included and managed by local pkg manager.

could you provide a light install script like Easy Video Downloader,  see https://github.com/andy-portmen/native-client/releases.

in this case, the coapp could use local libs if installed. and user will not have to keep a large appimage and utils.

**Comment by paulrouget** [comment]
We could imagine offering a node-less and ffmpeg-less package, but we prefer to rely on static binaries and not rely on the linux distribution libraries as they all differ too much and would be it very hard to support.
