### ISSUE TITLE
Constant CPU usage for no reason. Code trustwothy?

### ISSUE THREAD

**Issue by navid-zamani** [aclap-dev/vdhcoapp#146]
Since there strangely is no bug tracker for DownloadHelper itself, I’ll report this here:

The Video DownloadHelper add-on constantly uses way more CPU than it should, even when no downloads are active, and nothing is watched in the browser.  

I don’t know how to start it, other than having downloaded a video previously in the same session (browser hasn’t been closed in-between), but I can reliably stop the CPU hogging, by disabling the Video DownloadHelper extension.

Browser: Firefox (has been the case for at least a year, probably several, so should be the case in any version)
OS: Linux/systemd/Mint (ditto)

EDIT (to fix bad wording): I am not sure the app is really trustworthy.   
So if nothing happens, we’re gonna have to look into if it does anything nefarious, and if it does, report it.

**Comment by TM818** [comment]
Any word on this? Video Download Helper is a pretty widely installed app and has been for a long time - did you find or get any confirmation it actually does contain malware?

**Comment by navid-zamani** [comment]
> Any word on this? 

I have not been able to pin the CPU usage down, unfortunately. Mainly due to lack of interest. I suspect it may be two add-ons constantly triggering each other due to changes in the page. But I left the add-on disabled, since I have to do work. So it is gone now, and I only enable VDH for when I need it. Which in only for sites which yt-dlp does not support for schizoid reasons.

But for the record: I did not imply there was malware inside. Don’t make that assumption. Logic is not binary but ternary: Yes | No | Dunno. … I’m not the news media. My questions are really just questions. :)

Ergo, this big only serves to catch others who moght have the same problem, and might investigate one step further… unless I have a real need to solve  tbis.

**Comment by kelvinwl** [comment]
It can be only a bad or even not present code optimization. 
I'm not having an urgent need to dive into it too, so I'm subscribed to this issue to get any update.

**Comment by paulrouget** [comment]
With the latest ffmpeg (v6) this doesn't seem to happen again. This should be fixed in the next upcoming release.
