### ISSUE TITLE
Suggestion: Rename net.downloadhelper.coapp-1.6.3 Home folder

### ISSUE THREAD

**Issue by jkemp814** [aclap-dev/vdhcoapp#147]
Great extension,

I would like to suggest renaming net.downloadhelper.coapp-1.6.3 to vdhcoapp. 

This long folder name is wrapping across three lines, causing my top row of folders to have extra space than all the other rows. This folder looks like something that should be under .config, but it's a program folder so I understand. 

Folder name looks hideous in Home folder.

**Comment by jkemp814** [comment]
![Screenshot from 2023-01-15 12-42-13](https://user-images.githubusercontent.com/12059343/212563453-72d90bac-4bbf-4352-8360-1977cc90177c.png)

**Comment by paulrouget** [comment]
Solved in master (vdhcoapp) and will be available in next release.
