### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by graemeg** [aclap-dev/vdhcoapp#148]
How hard would it be to get FreeBSD support. As it's a JavaScript application (I think), does it mean I can just follow the Linux build instructions, but replace the word Linux with FreeBSD?

**Comment by paulrouget** [comment]
Nope, little harder than that. Here are the instructions:

- first compile this build of ffmpeg for freebsd: https://github.com/aclap-dev/ffmpeg-static-builder
- then make pkg-fetch available for freebsd: https://github.com/vercel/pkg-fetch
- then adapt build.sh to support freebsd a target os

That's a lot of work, and the pkg-fetch team doesn't want to support freebsd.

Closing as we don't have the resources to support freebsd.
