### ISSUE TITLE
Video DownlopadHelper additional add on (using Flatpack Firefox) the add on path is Flatpack rejected   

### ISSUE THREAD

**Issue by pdcinc** [aclap-dev/vdhcoapp#151]
Instructions to connect VideoDownloadhefiles lper using Flatpack Firefox is requested to attach the additional software add on requested
by VideiDownloadHelper,, Debian or TAR file add on versions are not connected add on to Firefox Flatpack installed Videodownloadhelper

**Comment by paulrouget** [comment]
Is this still a problem with the latest version of Firefox? It's supposed to have been fixed.

**Comment by paulrouget** [comment]
Closing in favor of https://github.com/aclap-dev/vdhcoapp/issues/159
