### ISSUE TITLE
Video DownloadHelper Companion App 1.6.3   Debian and tar

### ISSUE THREAD

**Issue by pdcinc** [aclap-dev/vdhcoapp#152]
Video DownloadHelper Companion App 1.6.3   Debian and tar  versions need  further  instructions  to connect  using Flatpack Firefox
installation of  Video DownloadHelper ....     The OS used is Ubuntu Linux 22  Firefox  installed as  Flatpack

**Comment by paulrouget** [comment]
This should not be problem with the latest version of Firefox.
