### ISSUE TITLE
Max Youtube Resolution is 1080p with VDH for Linux 8.0.0.0 on Firefox (flat)

### ISSUE THREAD

**Issue by kennysgithub** [aclap-dev/vdhcoapp#153]
Before the Youtube rework (as of  4-5 months ago) I was able to download YT > 1080p. Now no higher-resolution hits show up in the drop-down.

Is this a known limitation, or the result of some change with YT?

Firefox 115.0.3 (64bit from .tar.gz), Linux Lubuntu (kernel 5.15.0-76), CoApp 1.6.3 .

**Comment by paulrouget** [comment]
@kennysgithub this repo is not about the DownloadHelper extension. I recommend you to post your question there: https://groups.google.com/g/video-downloadhelper-q-and-a
