### ISSUE TITLE
Usage documentation

### ISSUE THREAD

**Issue by samtuke** [aclap-dev/vdhcoapp#154]
Seems like the README is missing basic usage instructions. What commands are supported? The binary doesn't appear to have help built in - at least it doesn't support 'help' subcommands. How are we supposed to know how to use this app?

**Comment by paulrouget** [comment]
There's nothing more than the install command. It is used through the Native Messaging protocol: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging
