### ISSUE TITLE
Flatpack, Snap and Firefox

### ISSUE THREAD

**Issue by paulrouget** [aclap-dev/vdhcoapp#159]
I open this issue to gather all the filed issues that are related to **flatpack and/snap + firefox**.

Workarounds have been posted in all these issues. In recent version of Firefox those workarounds are not necessary anymore.

If you still have problem with Firefox, please let me know here.

Previous issues:

- https://github.com/aclap-dev/vdhcoapp/issues/139
- https://github.com/aclap-dev/vdhcoapp/issues/151
- https://github.com/aclap-dev/vdhcoapp/issues/137
- https://github.com/aclap-dev/vdhcoapp/issues/133
- https://github.com/aclap-dev/vdhcoapp/issues/128
- https://github.com/aclap-dev/vdhcoapp/issues/114
-

**Comment by MadMartian** [comment]
This is also an issue with the WaterFox fork, FlatPak and Snap are irrelevant in this case.

**Comment by nanu-c** [comment]
I had to run ` flatpak permission-set webextensions net.downloadhelper.coapp snap.firefox yes` to get it working on a fresh install today.

**Comment by paulrouget** [comment]
> I had to run ` flatpak permission-set webextensions net.downloadhelper.coapp snap.firefox yes` to get it working on a fresh install today.

That's probably because of this: https://github.com/aclap-dev/vdhcoapp/blob/master/README.md#ubuntu-firefox-missed-prompt

**Comment by paulrouget** [comment]
I recommend people to read our document describing most of the coapp issues on Linux: https://github.com/aclap-dev/video-downloadhelper/wiki/CoApp-not-recognized

Closing.
