### ISSUE TITLE
Build Target for Linux aarch64

### ISSUE THREAD

**Issue by JeremiahCornelius** [aclap-dev/vdhcoapp#166]
I've tried numerous tricks to build on Debian Linux 64-bit arm. These all fail at various points, although I can trick 1.6.3 to build all of the binary dependencies.

This target will be useful for a large number of SoC SBCs, like Raspberry Pi and the very fast boards from IndyDroid. I am running Ashahi Linux on a Macbook Pro M1, which is port-compatible with anything from Intel 64 and can easily handle any compilation task.

**Comment by paulrouget** [comment]
What's the issue?

This is supposed to work "out of the box". We are also about to release some builds in the coming days / week.

**Comment by JeremiahCornelius** [comment]
@paulrouget There's no build target defined for aarch64. The converter/build-apps.sh exits with a message about no target. I edited this to set 
HOST_PLATFORM=Linux
ARCH=aarch64
I also had to assign $ARCHSRCDIR as converter/build/linux/64/ to get to sucessful completion, and modify a number of if/fi stanzas to successfully build the dependency sources.

Gulp still doesn't work, tho' I played around with the gulpfile, and ensured the node/npm/gulp environment was correct.
The error is 
```
SyntaxError: Unexpected end of input
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at requireOrImport (/usr/share/nodejs/gulp-cli/lib/shared/require-or-import.js:19:11)
    at execute (/usr/share/nodejs/gulp-cli/lib/versioned/^4.0.0/index.js:37:3)
```
This is a lot of effort that probably can be solved with a proper build target for aarch64. I donated for the project on my MacOS installs, and am watermark-free.

I can thrash around in scripts, configs and makefiles, but everything should build more easily!
Thank you.

**Comment by paulrouget** [comment]
You're using a pretty old version of the code. Mind updating and giving it a try?

**Comment by JeremiahCornelius** [comment]
@paulrouget 
I have had success at last with a clean git clone, and a next-to-most-recent yt binary from their releases.
Numerous problems were encountered attempting builds on 2 different SBC platforms including RPi 4, with Debian Bullseye. The final blocker on these was a problem with yt building, and dpkg-deb insisting incorrect permissions on the control directory. The last of these wasn't correctable using chmod, on both ext4 and btrfs.

Success was in a Debian Sid QEMU VM on a Macbook Pro M1. The caveat is that Debian unstable's installable yt package errors out. I replaced this with the next-to-most-recent yt binary, and built clean in a very fast session.

I hope some of this is helpful for others, and informs your team somewhat. Of course, a repro of your build environment and specs would have yielded a success from start.

Thanks!

**Comment by paulrouget** [comment]
What is yt binary? Why do you need it?

> Numerous problems were encountered attempting builds on 2 different SBC platforms including RPi 4, with Debian Bullseye

Which problems?

> dpkg-deb insisting incorrect permissions on the control directory. The last of these wasn't correctable using chmod, on both ext4 and btrfs

How do you run build.sh to run into such issues? This is not supposed to require any special permissions.
Did you run with sudo at any point?

> I hope some of this is helpful for others, and informs your team somewhat

Well we need to see the error messages, and understand what that `yt` thing is.

>  a repro of your build environment and specs would have yielded a success from start.

We provide a heath check at runtime. We will also list the requirements. But keep in mind master is still a WIP branch.

**Comment by JeremiahCornelius** [comment]
> What is yt binary? Why do you need it?
My bad in typing. It's `yq`  not yt. It parses the test input to build configuration

> 
> Which problems?
> 
> > dpkg-deb insisting incorrect permissions on the control directory. The last of these wasn't correctable using chmod, on both ext4 and btrfs
> 

Mostly the deb failing to build - because the control directory reports as 2755 permissions, not 0755. I have debroot installed. I used chmod and even setfacl, but nothing was changing the control directory permissions reported in the building process, even though `ls` reported 0755. I think this may be an upstream problem.

> How do you run build.sh to run into such issues? This is not supposed to require any special permissions. Did you run with sudo at any point?

I ran build.sh as a regular user. I did use `sudo` as part of exploratory troubleshooting, but did `chown -R *` on my clone after this didn't change behavior.

> > I hope some of this is helpful for others, and informs your team somewhat
> 
> Well we need to see the error messages, and understand what that `yt` thing is.
> 
> > a repro of your build environment and specs would have yielded a success from start.
> 
> We provide a heath check at runtime. We will also list the requirements. But keep in mind master is still a WIP branch.
>
Thanks for your time and help!

— Jeremiah

**Comment by paulrouget** [comment]
> the control directory reports as 2755 permissions, not 0755.

The control directory is just created with a regular mkdir. I'm suspecting an issue on your end (maybe the early `sudo` you used).

I'm gonna close this as it's working properly on a few platforms.

I think I could improve the requirements list (in particular the `yq` version).
