### ISSUE TITLE
Installer needs admin rights

### ISSUE THREAD

**Issue by mtayeldev** [aclap-dev/vdhcoapp#169]
Why does the installer need admin rights? there should be no reason why this app needs admin rights.

**Comment by paulrouget** [comment]
Which operating system, which version of the coapp?

**Comment by mtayeldev** [comment]
1.6.3, windows

**Comment by paulrouget** [comment]
Absolutely agreed. I'll look into it.

**Comment by paulrouget** [comment]
Fixed in upcoming 2.0.1 version.
