### ISSUE TITLE
When running coapp from command line, show some feedback and diagnostic

### ISSUE THREAD

**Issue by paulrouget** [aclap-dev/vdhcoapp#170]
We could do that on stderr.

**Comment by kuanyui** [comment]
Or maybe not on stderr. How about "when an option like `--help` or `--diagnose` existed, just print message and exit immediately"?

**Comment by paulrouget** [comment]
There's already --help and --version. We could add a --diagnose that does some checks. But I think we should print something if the app is started without options.

Wondering what the diagnostic function could do though. 99% of the problems come from the browser's sandbox, which can't be debugged from within the coapp.

**Comment by kuanyui** [comment]
I asked this because I've tried `--help` and `--version` but nothing output... Built and installed from AUR in 2023/08/02.
![Screenshot_20230927_130637](https://github.com/aclap-dev/vdhcoapp/assets/1370070/6c2e9ef7-3485-4fce-af43-361e5c21d121)

**Comment by paulrouget** [comment]
The wrong-path issue, and the command line option missing, it's all fixed in the upcoming version.

I will add a message inspired to what you just wrote here. Thanks!

**Comment by paulrouget** [comment]
Fixed in v2.0.2
