### ISSUE TITLE
Video Downloads as either audio only or video only

### ISSUE THREAD

**Issue by MadMartian** [aclap-dev/vdhcoapp#171]
Sometimes downloading a video from a non-YT source will download the video without audio.  There is also an option to download the audio separately.

![image](https://github.com/aclap-dev/vdhcoapp/assets/2112359/8d1f9888-53fd-4d1d-bcfb-d5c09a4ff39a)

A suitable work-around for this issue is running the following `ffmpeg` command:
```
ffmpeg -i "video.mp4" -i "audio-only.aac" -c:v copy -c:a copy "fixed-av.mp4"
```

**Comment by paulrouget** [comment]
@MadMartian this is fixed in the upcoming release (2.0.1).
