### ISSUE TITLE
vdhcoapp 2.0.2 doesn't work in Firefox flatpak "out of the box" as readme suggests

### ISSUE THREAD

**Issue by pizzadude** [aclap-dev/vdhcoapp#174]
vdhcoapp 2.0.2 doesn't work in Firefox flatpak "out of the box" as readme suggests

I still had to copy the "net.downloadhelper.coapp.json" from ~/.mozilla/native-messaging-hosts to ~/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts and whitelist the vdhcoapp directory via flatseal / flatpak override.

It is properly installed for chromium based flatpaks, however.

**Comment by paulrouget** [comment]
Which version of Firefox are you using?
How did you install the coapp (deb or tarball)?

**Comment by pizzadude** [comment]
latest firefox flatpak

coapp tarball

**Comment by paulrouget** [comment]
Erg, I mixed up the snap and flatpak Firefox status. 1ef6d836250452ddd8e28e43922c646f81d0b26a fixes it. I'll publish 2.0.3 later this week.

**Comment by paulrouget** [comment]
@pizzadude mind trying version 2.0.3 ? It should work out of the box this time.

**Comment by pizzadude** [comment]
I tested 2.0.3 and it still doesn't work out of the box. 

```
Installing…
Flatpak is installed. Making the coapp available from browser sandboxes:
Linked coapp within com.brave.Browser.
Linked coapp within com.google.Chrome.
Linked coapp within com.google.ChromeDev.
Linked coapp within org.chromium.Chromium.
Linked coapp within com.github.Eloston.UngoogledChromium.
Linked coapp within com.microsoft.Edge.
Linked coapp within com.microsoft.EdgeDev.
Writing /home/user/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json
Writing /home/user/.config/google-chrome/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /home/user/.config/chromium/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /home/user/.config/vivaldi/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /home/user/.config/opera/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /home/user/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser/NativeMessagingHosts/net.downloadhelper.coapp.json
VdhCoApp : VdhCoApp is ready to be used

```

It isn't installed in ~/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts and there is no flatpak override made for the firefox flatpak. Looking at the source code for vdhcoapp, there is no code for installing net.downloadhelper.coapp.json for the firefox flatpak and no flatpak override script for the firefox flatpak.

**Comment by paulrouget** [comment]
Thanks for helping out.

I only fixed the override, I didn't fix the file creation part.
Do you mind redownloading the v2.0.3 and giving it another go?

I tested locally and seems to work proper.

**Comment by pizzadude** [comment]
It works now, thanks. :)
