### ISSUE TITLE
Video only becomes 40 MB long MP4

### ISSUE THREAD

**Issue by marcoagpinto** [aclap-dev/vdhcoapp#179]
Hello!

I downloaded a 5-hour 1080p video from YouTube and after spending hours downloading, it became 40 MB long.

Then I tried a shorter video download also in 1080p and MP4, and it too became 40 MB long.

Is it a known issue?

EDIT: I am using Windows 11 and the latest Firefox.

EDIT2: Video: https://www.youtube.com/watch?v=0rYRpXFpMHw

Thanks!

**Comment by paulrouget** [comment]
Thanks for the report.

I recommend that you post on the google group for support: https://groups.google.com/g/video-downloadhelper-q-and-a
And there, please share the version of the addon and of the coapp you're using.
