### ISSUE TITLE
Tor support

### ISSUE THREAD

**Issue by paulrouget** [aclap-dev/vdhcoapp#181]
See https://groups.google.com/g/video-downloadhelper-q-and-a/c/FROKWGBR0yk/m/-kBVGZ0sDgAJ

**Comment by paulrouget** [comment]
We need to figure out the proper profile directory for Tor on Linux and Mac, and the Windows registry key.

**Comment by shobee** [comment]
I suppose on Mac it is `~/Library/Application\ Support/TorBrowser-Data/Browser`. Hope this helps.

**Comment by paulrouget** [comment]
There's no way of doing this without spawning a Tor proxy Coapp-side. It's not something I'm planning to work on anytime soon.

**Comment by paulrouget** [comment]
w

**Comment by AminFarhang** [comment]
Before your latest update, it was working properly on Tor.

**Comment by plin2** [comment]
Hi,

after several hours/days of analyzing the solution was quite simple. The following steps were executed on an OpenSUSE Leap 15.5 system with the Tor Browser from the distribution, but should work for the other Linux versions as well:

- I downloaded and installed the co-app as described for Linux giving output like
   Writing /home/peter/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json
   Writing /home/peter/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json
   Writing /home/peter/.config/chromium/NativeMessagingHosts/net.downloadhelper.coapp.json

-  I started the torbrowser with strace:
     strace -f -o strace.log torbrowser-launcher

- navigated to a video that I want to download, started the download and got the error message regarding the coapp not being installed

- closed the torbrowser 
 
- grep coapp strace.log
...
3654  openat(AT_FDCWD, "/home/peter/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json", O_RDONLY <unfinished ...>
3654  openat(AT_FDCWD, "/usr/lib/mozilla/native-messaging-hosts/net.downloadhelper.coapp.json", O_RDONLY <unfinished ...>
3654  openat(AT_FDCWD, "/home/peter/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json", O_RDONLY <unfinished ...>
3654  openat(AT_FDCWD, "/usr/lib/mozilla/native-messaging-hosts/net.downloadhelper.coapp.json", O_RDONLY <unfinished ...>
3811  sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="8\1\0\0\4\0\0\0\23\0q\0\1\0\0\0\0\0\0\0\377\377\377\377\350\377\377\377(\0\0\0"..., iov_len=64}, {iov_base="loadhelper.net/install-coapp-v2?"..., iov_len=280}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT <unfinished ...>
3811  sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="4\1\0\0\4\0\0\0\24\0q\0\1\0\0\0\0\0\0\0\377\377\377\377\303\377\377\377(\0\0\0"..., iov_len=64}, {iov_base="loadhelper.net/install-coapp-v2?"..., iov_len=276}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT <unfinished ...>
peter@dyn240:~/temp> 
...

- checked all the files from above that Downloadhelper tried to open regarding their existence, e.g. 
ls /home/peter/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json
ls: Zugriff auf '/home/peter/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json' nicht möglich: Datei oder Verzeichnis nicht gefunden

- none of them was found

- the installation log of the co-app showed me that a json file was placed at /home/peter/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json

- I created a path where Downloadhelper has been searching for that json file
mkdir -p /home/peter/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/

- copied one of the json files to that directory
cp /home/peter/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json /home/peter/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/

- checked for the existence of a file 
ls /home/peter/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json
=>
/home/peter/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json

The environment was fine now. I started the torbrowser-launcher and the coapp worked fine.

**Comment by woheller69** [comment]
``=>
/home/peter/.local/share/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json``

works like a charm

**Comment by shobee** [comment]
Thanks for your great effort! I had to copy the file to `~/Library/Application Support/TorBrowser-Data/Browser/Mozilla/NativeMessagingHosts` and now it works fine.

**Comment by AminFarhang** [comment]
Thanks @shobee it is now working fine for me by just coping the already installed coapp for Mozilla to your mentioned folder

`cp /Library/Application Support/Mozilla/NativeMessagingHosts/net.downloadhelper.coapp.json /Users/amin/Library/Application Support/TorBrowser-Data/Browser/Mozilla/NativeMessagingHosts`

**Comment by lfg-max** [comment]
Just do this simple step for Mac and you are done



https://github.com/aclap-dev/video-downloadhelper/discussions/912


This is a better solution and a simple file copy from. one location to another.

**Comment by lfg-max** [comment]
Just do this simple step for Mac and you are done



https://github.com/aclap-dev/video-downloadhelper/discussions/912


This is a better solution and a simple file copy from. one location to another.

**Comment by MarkCallow** [comment]
> There's no way of doing this without spawning a Tor proxy Coapp-side. It's not something I'm planning to work on anytime soon.

I don't understand. According to the [README](https://github.com/aclap-dev/vdhcoapp)

> DownloadHelper CoApp is a multi-platform (Windows, Mac, Linux) application providing the [Video DownloadHelper](https://downloadhelper.net/) browser add-on with a set of extra features not available directly from the add-on:
>
> - file writing API
> - launching default video player application on a data file
> - a build of the [ffmpeg](http://ffmpeg.org/) video converter

which suggests no network access so why is a proxy necessary? Isn't Tor just another custom install location?

**Comment by NervenCid** [comment]
Hello, i am using Ubuntu 24.04: 

And copied the file "net.downloadhelper.coapp.json" to the dir as the instructions above follows, and verified the location of the file:

![Image](https://github.com/user-attachments/assets/08cab4ad-37a6-4489-8656-8cb6c47f9de9)

But TOR browser keeps searching for the app for minutes, without being able to find it:

![Image](https://github.com/user-attachments/assets/a602ccce-d170-498d-9c99-d7619f168453)

Shall i modify the json file?

Thank you and sorry for my English

**Comment by MarkCallow** [comment]
> I don't understand. According to the [README](https://github.com/aclap-dev/vdhcoapp)

The README is incomplete. Last time I started Tor the extension displayed a page in which it said that for certain video formats it passes the URL to the CoApp which access the URL directly and it asked me to agree to the CoApp privacy policy or check a box to tell it not to use the CoApp for these formats. I've been unable to find that page again so can't paste the content here.
