### ISSUE TITLE
Question regarding external video players 

### ISSUE THREAD

**Issue by xd003** [aclap-dev/vdhcoapp#182]
i see ```launching default video player application on a data file``` mentioned in the readme as a feature of this companion app. Does this mean whatever video i am playing in browser can by directly launched in a external video player of my choice ?

**Comment by paulrouget** [comment]
> i see `launching default video player application on a data file` mentioned in the readme as a feature of this companion app. Does this mean whatever video i am playing in browser can by directly launched in a external video player of my choice ?

Absolutely! That's what the [Download Helper addon](https://www.downloadhelper.net/) is for.

I recommend asking usage-specific questions here: https://groups.google.com/g/video-downloadhelper-q-and-a

**Comment by xd003** [comment]
> > i see `launching default video player application on a data file` mentioned in the readme as a feature of this companion app. Does this mean whatever video i am playing in browser can by directly launched in a external video player of my choice ?
> 
> Absolutely! That's what the [Download Helper addon](https://www.downloadhelper.net/) is for.
> 
> I recommend asking usage-specific questions here: https://groups.google.com/g/video-downloadhelper-q-and-a

Sorry for commenting here but i did asked over at the google group discussions, someone told that external video player thing is only for videos already downloaded using mpv not for videos playing in the browser window. Can you please confirm this because while playing the video in browser, i don't see any option to launch external video player in videodownload helper extension setting in browser toolbar

**Comment by paulrouget** [comment]
> > > i see `launching default video player application on a data file` mentioned in the readme as a feature of this companion app. Does this mean whatever video i am playing in browser can by directly launched in a external video player of my choice ?
> > 
> > 
> > Absolutely! That's what the [Download Helper addon](https://www.downloadhelper.net/) is for.
> > I recommend asking usage-specific questions here: https://groups.google.com/g/video-downloadhelper-q-and-a
> 
> Sorry for commenting here but i did asked over at the google group discussions, someone told that external video player thing is only for videos already downloaded using mpv not for videos playing in the browser window. Can you please confirm this because while playing the video in browser, i don't see any option to launch external video player in videodownload helper extension setting in browser toolbar. i am confused since you said yes in your earlier statement

I replied there.
