### ISSUE TITLE
If the app is not recognized, please look at this first!

### ISSUE THREAD

**Issue by paulrouget** [aclap-dev/vdhcoapp#189]
Read this: https://github.com/aclap-dev/video-downloadhelper/wiki/CoApp-not-recognized

**Comment by nutpantz** [comment]
any idea how to install the app to work with firejail?

**Comment by nutpantz** [comment]
at least in ubuntu 
it seems if you copy  "net.downloadhelper.coapp.json" from the user path  /home/user/.mozilla/native-messaging-hosts
to the firejail sandbox path it will work ie /home/user/firejailpath/.mozilla/native-messaging-hosts

**Comment by paulrouget** [comment]
> at least in ubuntu it seems if you copy "net.downloadhelper.coapp.json" from the user path /home/user/.mozilla/native-messaging-hosts to the firejail sandbox path it will work ie /home/user/firejailpath/.mozilla/native-messaging-hosts

It worked for you?

**Comment by nutpantz** [comment]
Yes.

**Comment by paulrouget** [comment]
I've updated the troubleshooting section. Thank you!

**Comment by berdavcn** [comment]
If you're using Chrome on Debian you must make executable /home/davideb/.config/google-chrome/NativeMessagingHosts/net.downloadhelper.coapp.json

**Comment by paulrouget** [comment]
> If you're using Chrome on Debian you must make executable /home/davideb/.config/google-chrome/NativeMessagingHosts/net.downloadhelper.coapp.json

For real? I'd be surprised that's correct.
