### ISSUE TITLE
vdhcoapp runs but is not recognized (KDE Neon)

### ISSUE THREAD

**Issue by madmaxoft** [aclap-dev/vdhcoapp#191]
VDH doesn't work for me, it seems unable to talk to vdhcoapp. In the Extension settings, it says "Verifying Companion App…", with Recheck and Install buttons. Clicking the Recheck button does nothing.

I've tried following all the troubleshooting steps I could find - reinstall the extension, reinstall vdhcoapp, updated the extension to beta, verifying that vdhcoapp is installed and the native app runs fine (displays a message upon being run), the native manifests are in place and seem correct. I used `bpftrace` and found out that Firefox actually starts the native app when clicking the Recheck button, so it seems the registration is working fine.

```
Video DownloadHelper 8.1.3.0a1 (beta)
Video DownloadHelper
Version 8.1.3.0a1 (beta)
Browser locale: en-US
Production build
Built on dim. 31 déc. 2023 10:59:11 UTC
Build options: browser=firefox, linuxlic=false, noyt=false

Platform Linux x86-64
Browser Mozilla Firefox 121.0
```

I'm using KDE Neon 5.27, which in my understanging is built on top of Ubuntu 22.04. Firefox was installed via `apt`, not snap nor flatpak.

I'm out of ideas on what to check next.

**Comment by madmaxoft** [comment]
I've tried with vdhcoapp version 1.6.3 and 2.0.10, the results are the same with both versions.

**Comment by paulrouget** [comment]
Can you run `/opt/vdhcoapp/vdhcoapp install` (not as root) and print the output of `/opt/vdhcoapp/vdhcoapp --info`.

**Comment by paulrouget** [comment]
I just realized that you only see "Verifying Companion App…". It stays stuck that way?

And I imagine restarting Firefox doesn't solve the issue, correct?

**Comment by madmaxoft** [comment]
Here's the output of the commands:

```
xoft@asaga:~$ /opt/vdhcoapp/vdhcoapp install
Installing…
Flatpak is installed. Making the coapp available from browser sandboxes:
Linked coapp within org.mozilla.firefox.
Linked coapp within com.brave.Browser.
Linked coapp within com.google.Chrome.
Linked coapp within com.google.ChromeDev.
Linked coapp within org.chromium.Chromium.
Linked coapp within com.github.Eloston.UngoogledChromium.
Linked coapp within com.microsoft.Edge.
Linked coapp within com.microsoft.EdgeDev.
Writing /home/xoft/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json
Writing /home/xoft/.var/app/org.mozilla.firefox/.mozilla/native-messaging-hosts/net.downloadhelper.coapp.json
Writing /home/xoft/.config/google-chrome/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /home/xoft/.config/chromium/NativeMessagingHosts/net.downloadhelper.coapp.json
VdhCoApp : VdhCoApp is ready to be used
```

```
xoft@asaga:~$ /opt/vdhcoapp/vdhcoapp --info
{
  "id": "net.downloadhelper.coapp",
  "name": "VdhCoApp",
  "version": "2.0.10",
  "binary": "/opt/vdhcoapp/vdhcoapp",
  "displayName": "VdhCoApp",
  "description": "Video DownloadHelper companion app",
  "target": {
    "os": "linux",
    "arch": "x86_64",
    "node": "18"
  },
  "home": "/home/xoft",
  "converterBinary": "/opt/vdhcoapp/ffmpeg",
  "converterBase": "ffmpeg",
  "converterBaseVersion": "6.0"
}
```

Restarting Firefox doesn't solve the issue. The "Verifying Companion App…" stays stuck.

**Comment by jmgfr** [comment]
Hi, 

I have the same problem with firefox on KDE neon 5.27 installed by apt, but not with firefox downloaded directly on mozilla.org. (in tar.bz2 format)

So, It seem to be only with the kde (ubuntu) build version.

**Comment by paulrouget** [comment]
Are both of you sure that KDE Neon doesn't use sandboxed versions of Firefox? (Flatpak/Snap/AppArmor)?

**Comment by paulrouget** [comment]
Just to be sure, maybe try this?
https://github.com/aclap-dev/vdhcoapp/blob/master/doc/Troubleshooting.md#ubuntu-and-flatpak--snap-based-distributions

**Comment by jmgfr** [comment]
> Are both of you sure that KDE Neon doesn't use sandboxed versions of Firefox? (Flatpak/Snap/AppArmor)?

This effectively Apparmor rules for me :-(
Syslog say :
audit: type=1400 audit(1704214940.230:267): apparmor="DENIED" operation="exec" class="file" profile="firefox" name="/opt/vdhcoapp/vdhcoapp" pid=26532 comm=444F4D20576F726B6572 requested_mask="x" denied_mask="x" fsuid=1000 ouid=502

So, ti can be fixed by :
add "/opt/vdhcoapp/vdhcoapp ux," in  /etc/apparmor.d/local/usr.bin.firefox
restarting apparmor.service

**Comment by paulrouget** [comment]
@jmgfr thank you! That's useful. Adding that to our troubleshooting guide.
