### ISSUE TITLE
Companion App 2 not found (Firefox Beta + Ubuntu)

### ISSUE THREAD

**Issue by knaremus** [aclap-dev/vdhcoapp#192]
Firefox version for Ubuntu - 122.0b4 (64-bit) 

installed
VDH - 8.1.3.0a1 (beta)
https://www.downloadhelper.net/firefox/betas
and
vdhcoapp-2.0.10-linux-x86_64.tar.bz2
and
https://github.com/aclap-dev/vdhcoapp/blob/master/doc/Troubleshooting.md#ubuntu-and-flatpak--snap-based-distributions

// with Version 8.0.0.6 (latest stable release) also not work

//previously worked
//VDH for Firefox - 8.0.0.6 and
//net.downloadhelper.coapp-1.6.3-1_amd64
//from home/user

![Снимок экрана от 2024-01-02 23-54-24](https://github.com/aclap-dev/vdhcoapp/assets/155488623/b5ef25d2-50dc-4e37-acc0-b8cfcf39c586)
![Снимок экрана от 2024-01-02 23-54-34](https://github.com/aclap-dev/vdhcoapp/assets/155488623/6f266ed3-3280-427f-9ef6-fb447dc7da42)
![Снимок экрана от 2024-01-03 00-01-37](https://github.com/aclap-dev/vdhcoapp/assets/155488623/06d890ed-2f14-4783-8e43-ccaef32a89de)

**Comment by paulrouget** [comment]
Did you also try:

```
flatpak permission-set webextensions net.downloadhelper.coapp snap.firefox yes
```

Then restart Firefox.

**Comment by knaremus** [comment]
yes 
but restarting Firefox doesn't help

**Comment by paulrouget** [comment]
Oh, so you use Firefox Beta.

How did you install Firefox Beta?

**Comment by paulrouget** [comment]
If you installed it as a snap, can you run this:

```
flatpak permissions webextensions
```

and tells me what it says.

**Comment by knaremus** [comment]
Firefox Beta was probably updated via Ubuntu Software.
I reinstalled Firefox (but the version connected - 8.0.0.6). Now version Firefox 121.00 - Companion app 2.0.10 successfully found.

I think the problem has been resolved.
Will I need to update VDH to a new version later?

![Снимок экрана от 2024-01-03 13-19-17](https://github.com/aclap-dev/vdhcoapp/assets/155488623/7cd542f1-544b-4a04-9f81-de4a6bc716c6)

**Comment by paulrouget** [comment]
> Will I need to update VDH to a new version later?

No, no need.
