### ISSUE TITLE
Error using/loading on Mac OS Sonoma 14.2.1

### ISSUE THREAD

**Issue by fangme** [aclap-dev/vdhcoapp#196]
All was working before, but I updated FF, and got a message I needed to update the companion app.  The page I go to identifies the browser as Chrome, but it is FF.  (https://www.downloadhelper.net/install-coapp-v2?browser=chrome)

That page tells me there is NO compatible version of the companion app (version listed is vdhcoapp-2.0.10-mac-x86_64.dmg. I'm on an Intel Mac.

I keep getting an error that the companion app cannot be found.  Not sure what the prior version of the helper app was, but it worked fine, with the previous release of FF (I update FREQUENTLY).

**Comment by paulrouget** [comment]
> That page tells me there is NO compatible version of the companion app

What do you mean? It doesn't recommend you vdhcoapp-2.0.10-mac-x86_64-installer.pkg (or the dmg) ?

If you install the DMG (we recommend the PKG) did you start the coapp at least once?

**Comment by fangme** [comment]
Yes started it - the extension still says it isn’t installed when trying to “recheck”  Still says to install.

I’ve installed the dmg originally (a few years ago), and it’s worked.  WIth this issue, I’ve uninstalled the dmg, and installed the pkg - still get the same issue.

I’ll try to uninstall FF, and reinstall

**Comment by fangme** [comment]
Reinstalling FF and the extension seems to have worked for FF.

I’ve got one or two other FF derived browsers I’ll have to test in the next day or so (Tor as one) - see what happens there

**Comment by paulrouget** [comment]
Can you install the Intel PKG them, open the "Terminal" application, and type:

```
/Applications/net.downloadhelper.coapp.app/Contents/MacOS/vdhcoapp --info
```

Let me know the output.

**Comment by fangme** [comment]
Output is:

{
  "id": "net.downloadhelper.coapp",
  "name": "VdhCoApp",
  "version": "2.0.10",
  "binary": "/Applications/net.downloadhelper.coapp.app/Contents/MacOS/vdhcoapp",
  "displayName": "VdhCoApp",
  "description": "Video DownloadHelper companion app",
  "target": {
    "os": "mac",
    "arch": "x86_64",
    "node": "18"
  },
  "home": "/Users/tim",
  "converterBinary": "/Applications/net.downloadhelper.coapp.app/Contents/MacOS/ffmpeg",
  "converterBase": "ffmpeg",
  "converterBaseVersion": "6.0"
}

If the extension says it can’t find the companion app - what is done by the extension to detect if net.downloadhelper.coapp?  Is it trying to run the above?  Or just a directory search to see if it’s there?  Or ??

Wondering if a permissions problem might be the issue I was seeing.  And it isn’t detected in Tor (which is FF based), even after reinstalling Tor and the latest version of the extension 8.1.4.0.  Latest FF says “Companion App installed”, and latest Tor says “Companion App not installed"

**Comment by paulrouget** [comment]
If you run:

```
/Applications/net.downloadhelper.coapp.app/Contents/MacOS/vdhcoapp install
```

in your terminal, what does it say?

As for Tor, it [won't work](https://github.com/aclap-dev/vdhcoapp/issues/181#issuecomment-1891199897).

**Comment by fangme** [comment]
Responded with:

Installing…
Writing /Users/tim/Library/Application Support/Mozilla/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /Users/tim/Library/Application Support/Vivaldi/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /Users/tim/Library/Application Support/Google/Chrome Beta/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /Users/tim/Library/Application Support/Google/Chrome Canary/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /Users/tim/Library/Application Support/Google/Chrome Dev/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /Users/tim/Library/Application Support/Google/Chrome/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /Users/tim/Library/Application Support/Microsoft Edge Beta/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /Users/tim/Library/Application Support/Microsoft Edge Canary/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /Users/tim/Library/Application Support/Microsoft Edge Dev/NativeMessagingHosts/net.downloadhelper.coapp.json
Writing /Users/tim/Library/Application Support/Microsoft Edge/NativeMessagingHosts/net.downloadhelper.coapp.json
VdhCoApp : VdhCoApp is ready to be used

And the popup notification occurred on my mac.

I see FF isn’t in the list, nor is Tor.  HOWEVER, FF shows the helper app is enabled, and so does Mullvad (based on Tor, version 13.0.7 based on Mozilla Firefox 115.6.0esr).  Mullvad indicates “Companion App installed”

FF is version 121.0.1 (64-bit), and also indicates “Companion App installed”
Tor is version 13.0.8 (based on Mozilla Firefox 115.6.0esr) and indicates “Companion App NOT installed”

I don’t use Chrome, and don’t use extensions in Edge.  I use Edge ONLY to make use of the OneNote web clipper extension.

**Comment by paulrouget** [comment]
> I see FF isn’t in the list, nor is Tor.

They are. See the "Mozilla" reference.

> FF shows the helper app is enabled

Cool!

For others:

if you install the DMG, do not forget to run the app after install. Or run the command line as explained above.
