### ISSUE TITLE
 VdhCoApp 2.0.10 window cannot capture sound

### ISSUE THREAD

**Issue by mojibiz00** [aclap-dev/vdhcoapp#197]
VdhCoApp 2.0.10  firefox add-on Video DownloadHelper cannot capture sound and only video was downloaded. Windows x86-64 Mozilla Firefox 121.0  Video DownloadHelper 8.1.4.0. prior version was just functional, but the update caused issues.

**Comment by paulrouget** [comment]
Please let me know which website.

**Comment by mojibiz00** [comment]
downloaded video from this site is not containing sound. 
https://www3.nhk.or.jp/news/movie.html

**Comment by paulrouget** [comment]
I see that those pages have different sources, one without sound. Gonna see how to make sure we select the correct one.

**Comment by paulrouget** [comment]
I'm getting more reports about this. Seems that I can happen mid video too.

**Comment by paulrouget** [comment]
Migrating the conversation to our forum: https://github.com/aclap-dev/video-downloadhelper/discussions/6
