### ISSUE TITLE
vdhcoapp-2.0.10 not working with Firefox

### ISSUE THREAD

**Issue by oldpink** [aclap-dev/vdhcoapp#202]
Since auto-upgrading to VDH 8.1.4.0 prompted me to upgrade to vdhcoapp-2.0.10, I followed the instructions, using the file vdhcoapp-2.0.10-linux-x86_64.tar.bz2 and intending it to be a system-wide install, simply using "/opt/vdhcoapp-2.0.1/vdhcoapp" as the command to install that way.
Sadly, no matter how hard I try to understand it, my browser of choice, Firefox, fails to recognize it at all.
I have no idea where the .json file that apparently needs to be for Firefox to even detect it.
If I had a type of alternative set of commands to manually get Firefox to detect it, I would use that, but as of now, VDH is useless to me until I can get some help finding a solution.
Does anyone have any suggestions?

**Comment by paulrouget** [comment]
I need to know which type of Firefox you're using (portable, snap, flatpak, etc…).

Look at the "Ubuntu" section here: https://github.com/aclap-dev/vdhcoapp/blob/master/doc/Troubleshooting.md

**Comment by oldpink** [comment]
It's version 121.0.1, compiled on Slackware Linux.
Not portable or some other special version.

**Comment by paulrouget** [comment]
> It's version 121.0.1, compiled on Slackware Linux. Not portable or some other special version.

What does this say: `/opt/vdhcoapp/vdhcoapp --info` ?

And did you make sure to run the install command as a non-root user?

`/opt/vdhcoapp/vdhcoapp install`

**Comment by oldpink** [comment]
Output of /opt/vdhcoapp/vdhcoapp --info

{
  "id": "net.downloadhelper.coapp",
  "name": "VdhCoApp",
  "version": "2.0.10",
  "binary": "/opt/vdhcoapp-2.0.10/vdhcoapp",
  "displayName": "VdhCoApp",
  "description": "Video DownloadHelper companion app",
  "target": {
    "os": "linux",
    "arch": "x86_64",
    "node": "18"
  },
  "home": "/root",
  "converterBinary": "/opt/vdhcoapp-2.0.10/ffmpeg",
  "converterBase": "ffmpeg",
  "converterBaseVersion": "6.0"
}

I was trying to do a system-wide install, so no in answer to the second question.

**Comment by paulrouget** [comment]
Right, system wide installs are not recommended as they conflict with previously user-system installs.

Closing as I'm assuming the user-wide install works.

If that's not the case, please re-open this issue.

**Comment by oldpink** [comment]
But the instructions indicate that system-wide installs are still supported.
Is that incorrect?
I **have** no user-wide installs for vhdcoapp on this system that could cause conflicts.
This sounds like I'm being told to just abandon VDH entirely at this point.

**Comment by paulrouget** [comment]
> But the instructions indicate that system-wide installs are still supported.

Oh damn, you're correct! I just fixed it there. Thanks.

> I have no user-wide installs for vhdcoapp on this system that could cause conflicts.

Does this directory exist: `~/.mozilla/native-messaging-hosts/` ?

> This sounds like I'm being told to just abandon VDH entirely at this point.

Understood. I was trying to help. Have a good day.

---

For other people running into this issue:

If you're using non-deb based system, it's very likely you did a user-wide install of the coapp V1. So you also need to do a user-wide install of the coapp v2 (running `vdhcoapp install` as a user should do it). Another unsupported method is to remove the relevant json file from ~/.mozilla/native-messaging-hosts/ (which most likely points to the old coapp). That should make you v2 system wide install work as expected.
