### ISSUE TITLE
My resistration key for this app and the browser extensions completely disapearerd after upgrading them and now QRcode storms in video.

### ISSUE THREAD

**Issue by Stop-Unsecure-ZeroInstall-Updating** [aclap-dev/vdhcoapp#206]
Hello,

My licence for this app and the browser extensions disappeared after upgrading them. Please provide alternatives promptly. 

I already purchased the license for them, completely to prevent these apps from writing ugly QR codes in my precious videos never be recorded in the future. 

Additionally, there is critical error. 
 Even if I configure them just to record videos as is, they convert all videos and write ugly storms of QR codes into precious videos.
This is the error I wrote above.

First, please provide the license key string very promptly which works correctly and does not disappear after upgrading this app and the browser extensions.
 
Secondly, please fix the incorrect behaviour as I wrote, even if I configure them to recaord videos without any transformation, they transform videos and write QR codes in videos. 

Yours sincerely,
QED

**Comment by paulrouget** [comment]
This is a developer forum. To ask questions about Video DownloadHelper, please post there: https://groups.google.com/g/video-downloadhelper-q-and-a
