### ISSUE TITLE
`/opt/vdhcoapp/vdhcoapp install` does not create net.downloadhelper.coapp.json for flatpak-installed Edge despite linking itself in its sandbox

### ISSUE THREAD

**Issue by norweeg** [aclap-dev/vdhcoapp#207]
Similar to #131 , running `/opt/vdhcoapp/vdhcoapp install` will detect flatpak, link itself in all browser sandboxes (including flatpak-installed Google Chrome and Microsoft Edge), but it only creates `~/.var/app/com.google.Chrome/config/google-chrome/NativeMessagingHosts/net.downloadhelper.coapp.json` but not the corresponding `~/.var/app/com.microsoft.Edge/config/microsoft-edge/NativeMessagingHosts/net.downloadhelper.coapp.json` even though `~/.var/app/com.google.Chrome/config/google-chrome/NativeMessagingHosts/net.downloadhelper.coapp.json`  contains the correct allowed origin for the Edge Extension store version of the VDH extension.

**Comment by paulrouget** [comment]
If you copy ~/.var/app/com.google.Chrome/config/google-chrome/NativeMessagingHosts/net.downloadhelper.coapp.json to ~/.var/app/com.microsoft.Edge/config/microsoft-edge/NativeMessagingHosts/net.downloadhelper.coapp.json , does it work?

**Comment by paulrouget** [comment]
For some reasons, we do not create that file. Indeed.

Can you confirm it works? And I'll do a new release.

**Comment by norweeg** [comment]
> If you copy ~/.var/app/com.google.Chrome/config/google-chrome/NativeMessagingHosts/net.downloadhelper.coapp.json to ~/.var/app/com.microsoft.Edge/config/microsoft-edge/NativeMessagingHosts/net.downloadhelper.coapp.json , does it work?

yes, it does and that's what I did before reporting the bug since it just seemed like it was just overlooked because you link the vdhcoapp to the Edge sandbox (and other Chromium-based browsers) AND include the correct allowed origin in the net.downloadhelper.coapp.json installed for Chrome, but then not install the same file for Edge (and apparently Ungoogled-Chromium and likely none of the other Chromium-based browsers whose sandbox it was linked to either)

**Comment by norweeg** [comment]
> If you copy ~/.var/app/com.google.Chrome/config/google-chrome/NativeMessagingHosts/net.downloadhelper.coapp.json to ~/.var/app/com.microsoft.Edge/config/microsoft-edge/NativeMessagingHosts/net.downloadhelper.coapp.json , does it work?

yes, it does and that's what I did before reporting the bug since it just seemed like an oversight to link the vdhcoapp to the sandbox AND include the correct allowed origin in the net.downloadhelper.coapp.json installed for Chrome, but then not install the same file for Edge (and apparently Ungoogled-Chromium)

**Comment by paulrouget** [comment]
@norweeg thanks for your help.


This will be fixed in CoApp 2.0.14
