### ISSUE TITLE
Proxy feature not working

### ISSUE THREAD

**Issue by BdBAyif0oohO2N4K** [aclap-dev/vdhcoapp#210]
The feature "Coapp proxy" no long works on 2.x build. It worked on 1.x builds. However, as for newer builds coapp would never use proxy at all despite this option being selected.

**Comment by paulrouget** [comment]
We got a few reports about this! I'll be looking at it soon.

**Comment by paulrouget** [comment]
Dupe: https://github.com/aclap-dev/vdhcoapp/issues/209
