### ISSUE TITLE
replace filepicker with zenity

### ISSUE THREAD

**Issue by milahu** [aclap-dev/vdhcoapp#216]
replace [filepicker](https://github.com/paulrouget/static-filepicker) with something more popular

- [zenity](https://man.archlinux.org/man/zenity.1.en) - GTK
  - `zenity --title="open file" --file-selection`
  - `zenity --title="save file" --file-selection --save --filename=asdf.txt`
  - `zenity --title="open directory" --file-selection --directory`
- [kdialog](https://apps.kde.org/kdialog/) - Qt
  - `kdialog --getopenfilename`
  - `kdialog --getsavefilename`
  - `kdialog --getexistingdirectory`
- [nativefiledialog](https://github.com/btzy/nativefiledialog-extended) - GTK/native, no CLI app?
- [qarma](https://github.com/luebking/qarma) - Qt, clone of zenity
- [node-file-dialog](https://github.com/manorit2001/node-file-dialog), python tkinter
- [dialogbox](https://github.com/martynets/dialogbox/) - Qt, no file picker, create complex dialogs
  - `dialogbox <<<'add label "asdf" msg; add pushbutton &Ok okay apply exit'`
- [gtkdialog](https://github.com/oshazard/gtkdialog) - 10 stars, 10 years ago
- [dialog](https://invisible-island.net/dialog/dialog.html) - ncurses (terminal)

see also

- [cross platform native open/save file dialogs](https://stackoverflow.com/questions/6145910/cross-platform-native-open-save-file-dialogs)
- [How to open a "Select folder" dialog from NodeJS (server-side, not browser)?](https://stackoverflow.com/questions/51655571/how-to-open-a-select-folder-dialog-from-nodejs-server-side-not-browser)

**Comment by paulrouget** [comment]
Only [nativefiledialog](https://github.com/btzy/nativefiledialog-extended) works, but what's the point?

**Comment by milahu** [comment]
> what's the point?

using a tool that is more popular, to re-use existing tools from the system's package manager

but then, [paulrouget/static-filepicker](https://github.com/paulrouget/static-filepicker) is based on [rfd](https://github.com/PolyMeilex/rfd) - 500 stars, last commit 2024
and the build takes only some minutes, so... nevermind
