### ISSUE TITLE
How do I uninstall the helper app?

### ISSUE THREAD

**Issue by Ranko-Saotome** [aclap-dev/vdhcoapp#222]
I uninstalled the extension cuz I did not find it useful but I'm having a hard time uninstalling the helper I'm on zorin os

**Comment by paulrouget** [comment]
How did you install it?

If you use linux, and didn't use the deb file, best way is to run `vdhcoapp uninstall` to remove the manifest files from the mozilla profile, and then just remove the coapp install directory.

**Comment by Ranko-Saotome** [comment]
i figured it out!
