### ISSUE TITLE
Hello I just uninstalled and was wondering what this is and how do I revert it if it changed anything on my system (The linking part)

### ISSUE THREAD

**Issue by NKkrisz** [aclap-dev/vdhcoapp#227]
![image](https://github.com/aclap-dev/vdhcoapp/assets/41510145/b16c6495-45bb-4204-87af-0d5fd8855fc8)

**Comment by NKkrisz** [comment]
Why does it do anything after uninstalling even?
(I get the file removing part but why make the coapp available from browser sandboxes? And how do I revert that??)

**Comment by NKkrisz** [comment]
I think I may have figured it out, basically it gives a flatpak permission?

To check if you have it run:
`flatpak permissions`
![image](https://github.com/aclap-dev/vdhcoapp/assets/41510145/00214d83-7638-4c0f-981c-e023e7f7657a)


This is how I removed it:
`flatpak permission-remove webextensions net.downloadhelper.coapp`
![image](https://github.com/aclap-dev/vdhcoapp/assets/41510145/83b22a07-bd9f-4644-ab6a-f35e7275e3d1)

Is there anything else it does?

**Comment by paulrouget** [comment]
The coapp adds the permission to flatpak but also creates files under `.mozilla` and similar configuration directories for Chrome, Edge and other browsers.

As described right here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#linux

You can see the list of files here:

https://github.com/aclap-dev/vdhcoapp/blob/0b40d3e101c429fdae4e02ba1f593c2416b51eff/config.toml#L185C1-L263C38

Hope this answers your question :)

**Comment by NKkrisz** [comment]
Thank you for the quick answer, it's just confusing that an uninstall shows these messages, I think you should remove them.
