### ISSUE TITLE
Wait 120 minutes?

### ISSUE THREAD

**Issue by woeterman94** [aclap-dev/vdhcoapp#230]
Why do I need to wait 120 minutes? Or pay for a "premium license"?

**Comment by paulrouget** [comment]
That's how we support the development of downloadhelper :)

**Comment by woeterman94** [comment]
Would be better to work with donations that limiting users, don't you think?

**Comment by RedBluePrinter** [comment]
True. I am not a fan of Licenses. I would Donate tho :D

**Comment by RedBluePrinter** [comment]
> True. I am not a fan of Licenses. I would Donate tho :D

My Information could be outdated. I am using an older Version (Not Updated!)
