### ISSUE TITLE
Add build target for ARM64 (aarch64)

### ISSUE THREAD

**Issue by phred2** [aclap-dev/vdhcoapp#50]
(please)

**Comment by TobSeCretR** [comment]
That would be necessary for the raspery pi, too.

**Comment by DLGolden** [comment]
Is anyone already working on support for ARM64? I'm using Ubuntu 22.04 LTS on Raspberry PI4 and would really like to get this working. I think that most of the Raspberry PI's using GUI are running ARM64. Comments welcome.

**Comment by mi-g** [comment]
We (VDH team) are not working on this. The project being open-source, others might be working on this port but we haven't heard of such initiative.

**Comment by paulrouget** [comment]
aarch64 builds (both ffmpeg and coapp) are functional now. Well be part of the next release.
