### ISSUE TITLE
Companion App can not be found in Avast Secure Browser

### ISSUE THREAD

**Issue by TheBlue-1** [aclap-dev/vdhcoapp#90]
The companion app will not be found if you use Avast Secure Browser (Chrome based)

Avast Secure Browser: Version 88.2.8118.183
Companion App: 1.6.0
DownloadHelper: 7.5.0.3

**Comment by paulrouget** [comment]
Not planning to support Avast Secure Browser unless we get the Avast browser native messaging manifest directory (which I could not find online).

Feel free to re-open if anyone finds the location of that directory.
