### ISSUE TITLE
the app 1.6.3 cannot be opened in macOS 11.3.0

### ISSUE THREAD

**Issue by LatteCat** [aclap-dev/vdhcoapp#93]

**Comment by mi-g** [comment]
Can you open the finder, go to the downloads directory where the `.pkg` file is and open it from there ?

**Comment by TheLittleBoy** [comment]
The `.dmg` file cannot work, the `.pkg` file is OK.

**Comment by papakay** [comment]
It's not working on macOs 11.4. The installation is successful but the  app doesn't  open.

**Comment by YukunXia** [comment]
Same situation here. Both pkg and dmg don't work on macOS 11.1

**Comment by baptisteArno** [comment]
Same here, the app won't open on macOS 12.0.1

**Comment by watou** [comment]
1.6.3 will not install on macOS 11.6.1, either .pkg or .dmg

**Comment by Wayne-007** [comment]
the same to me

**Comment by jt196** [comment]
You'll need to unquarantine the pkg file. 

1. cd into the downloads folder
2. `xattr -d com.apple.quarantine net.downloadhelper.coapp-1.6.3.pkg`

**Comment by paulrouget** [comment]
Fixed in master. Will be part of the next release.
