### ISSUE TITLE
Problems in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by mnwstl** [aclap-dev/vdhcoapp#97]
In the user installation option runs well, however in the system installation option does not run. In the user installation option runs well, however in the system installation option does not run. Video DownloadHelper returns the message in Settings/ General/ Helper application not installed/ Checking the Returned Companion Application: An unexpected occurred error. 
Firefox 90.0.2 (64-bits).

**Comment by paulrouget** [comment]
Is it still happening?

**Comment by mnwstl** [comment]
> Is it still happening?

No, it doesn't happen to me anymore.
